apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whale-watcher
  name: pitbull-whale-watcher
  labels:
    app: pitbull-ww
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitbull-ww
  template:
    metadata:
      labels:
        app: pitbull-ww
    spec:
      containers:
        - name: pitbull-ww
          # Add your own personal registry here
          image: registry.dougflynn.dev/whale-watcher:pitbull
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred